@startuml
skinparam backgroundColor white

node "Cliente (Navegador/Desktop)" <<device>> {

  artifact "Frontend React"

}

cloud "Vercel Cloud" {

  artifact "frontend-build"

}

node "Servidor de Aplicacao\n(Node.js Runtime)" <<server>> {

  artifact "api-nodejs"

}

cloud "Railway Cloud" {

  artifact "deploy-backend"

}

cloud "Supabase Cloud" {

  database "PostgreSQL"

  component "Supabase Auth"

  component "Supabase Storage"

}

node "Portal da Transparencia" <<external>> {

  artifact "API REST Publica"

}


"Cliente (Navegador/Desktop)" -- "Vercel Cloud" : HTTPS

"Vercel Cloud" -- "Servidor de Aplicacao\n(Node.js Runtime)" : HTTPS / REST

"Servidor de Aplicacao\n(Node.js Runtime)" -- "Railway Cloud" : Deploy

"Servidor de Aplicacao\n(Node.js Runtime)" -- "Supabase Cloud" : REST API

"Servidor de Aplicacao\n(Node.js Runtime)" -- "Portal da Transparencia" : REST API
@enduml
